// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NVSSMessaging.Models;

namespace NVSSMessaging.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210707215530_StoreOriginalMessage")]
    partial class StoreOriginalMessage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NVSSMessaging.Models.FHIRMessageItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACKMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IJE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FHIRMessageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
