openapi: 3.0.1
info:
  title: NVSSMessaging
  version: v1
paths:
  '/{jurisdictionId}/Bundle':
    get:
      tags:
        - Bundles
      summary: "Retrieves outgoing messages for the jurisdiction\r\nIf the optional Certificate Number and Death year parameters are provided, retrieves all messages in history that match those given business ids."
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
        - name: _count
          in: query
          schema:
            type: integer
            format: int32
        - name: certificateNumber
          in: query
          schema:
            type: string
        - name: eventYear
          in: query
          schema:
            type: string
        - name: deathYear
          in: query
          schema:
            type: string
        - name: _since
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        '200':
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: { }
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
    post:
      tags:
        - Bundles
      summary: Submits a FHIR message to the API for processing
      description: "Sample request:\r\n            \r\n    POST\r\n            \r\n    {\r\n        \"resourceType\": \"Bundle\",\r\n        \"id\": \"bffdbf2e-c0db-49cf-9f52-59a6459635b9\",\r\n        \"type\": \"message\",\r\n        \"timestamp\": \"2022-07-27T15:30:39.5787234+00:00\",\r\n        \"entry\": [\r\n            { ...\r\n            }\r\n        ]\r\n    }"
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema: { }
          application/json:
            schema: { }
          text/json:
            schema: { }
          application/*+json:
            schema: { }
      responses:
        '204':
          description: Content created
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
  '/{jurisdictionId}/Bundle/{vitalType}/{igVersion}':
    get:
      tags:
        - Bundles
      summary: "Retrieves outgoing messages for the jurisdiction\r\nIf the optional Certificate Number and Death year parameters are provided, retrieves all messages in history that match those given business ids."
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            pattern: ^(VRDR|BFDR-BIRTH|BFDR-FETALDEATH)$
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
        - name: _count
          in: query
          schema:
            type: integer
            format: int32
        - name: certificateNumber
          in: query
          schema:
            type: string
        - name: eventYear
          in: query
          schema:
            type: string
        - name: deathYear
          in: query
          schema:
            type: string
        - name: _since
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        '200':
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: { }
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
    post:
      tags:
        - Bundles
      summary: Submits a FHIR message to the API for processing
      description: "Sample request:\r\n            \r\n    POST\r\n            \r\n    {\r\n        \"resourceType\": \"Bundle\",\r\n        \"id\": \"bffdbf2e-c0db-49cf-9f52-59a6459635b9\",\r\n        \"type\": \"message\",\r\n        \"timestamp\": \"2022-07-27T15:30:39.5787234+00:00\",\r\n        \"entry\": [\r\n            { ...\r\n            }\r\n        ]\r\n    }"
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            pattern: ^(VRDR|BFDR-BIRTH|BFDR-FETALDEATH)$
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema: { }
          application/json:
            schema: { }
          text/json:
            schema: { }
          application/*+json:
            schema: { }
      responses:
        '204':
          description: Content created
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
  '/{jurisdictionId}/Bundles':
    get:
      tags:
        - Bundles
      summary: "Retrieves outgoing messages for the jurisdiction\r\nIf the optional Certificate Number and Death year parameters are provided, retrieves all messages in history that match those given business ids."
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
        - name: _count
          in: query
          schema:
            type: integer
            format: int32
        - name: certificateNumber
          in: query
          schema:
            type: string
        - name: eventYear
          in: query
          schema:
            type: string
        - name: deathYear
          in: query
          schema:
            type: string
        - name: _since
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        '200':
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: { }
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
    post:
      tags:
        - Bundles
      summary: Submits a FHIR message to the API for processing
      description: "Sample request:\r\n            \r\n    POST\r\n            \r\n    {\r\n        \"resourceType\": \"Bundle\",\r\n        \"id\": \"bffdbf2e-c0db-49cf-9f52-59a6459635b9\",\r\n        \"type\": \"message\",\r\n        \"timestamp\": \"2022-07-27T15:30:39.5787234+00:00\",\r\n        \"entry\": [\r\n            { ...\r\n            }\r\n        ]\r\n    }"
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema: { }
          application/json:
            schema: { }
          text/json:
            schema: { }
          application/*+json:
            schema: { }
      responses:
        '204':
          description: Content created
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
  '/{jurisdictionId}/metadata':
    get:
      tags:
        - CapabilityStatement
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
      responses:
        '200':
          description: Success
  '/STEVE/{jurisdictionId}/Bundle':
    get:
      tags:
        - Steve
      summary: "Retrieves outgoing messages for the jurisdiction\r\nIf the optional Certificate Number and Death year parameters are provided, retrieves all messages in history that match those given business ids."
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
        - name: _count
          in: query
          schema:
            type: integer
            format: int32
        - name: certificateNumber
          in: query
          schema:
            type: string
        - name: eventYear
          in: query
          schema:
            type: string
        - name: deathYear
          in: query
          schema:
            type: string
        - name: _since
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        '200':
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: { }
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
    post:
      tags:
        - Steve
      summary: Submits a FHIR message to the API for processing
      description: "Sample request:\r\n            \r\n    POST\r\n            \r\n    {\r\n        \"resourceType\": \"Bundle\",\r\n        \"id\": \"bffdbf2e-c0db-49cf-9f52-59a6459635b9\",\r\n        \"type\": \"message\",\r\n        \"timestamp\": \"2022-07-27T15:30:39.5787234+00:00\",\r\n        \"entry\": [\r\n            { ...\r\n            }\r\n        ]\r\n    }"
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema: { }
          application/json:
            schema: { }
          text/json:
            schema: { }
          application/*+json:
            schema: { }
      responses:
        '204':
          description: Content created
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
  '/STEVE/{jurisdictionId}/Bundle/{vitalType}/{igVersion}':
    get:
      tags:
        - Steve
      summary: "Retrieves outgoing messages for the jurisdiction\r\nIf the optional Certificate Number and Death year parameters are provided, retrieves all messages in history that match those given business ids."
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            pattern: ^(VRDR|BFDR-BIRTH|BFDR-FETALDEATH)$
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
        - name: _count
          in: query
          schema:
            type: integer
            format: int32
        - name: certificateNumber
          in: query
          schema:
            type: string
        - name: eventYear
          in: query
          schema:
            type: string
        - name: deathYear
          in: query
          schema:
            type: string
        - name: _since
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        '200':
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: { }
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
    post:
      tags:
        - Steve
      summary: Submits a FHIR message to the API for processing
      description: "Sample request:\r\n            \r\n    POST\r\n            \r\n    {\r\n        \"resourceType\": \"Bundle\",\r\n        \"id\": \"bffdbf2e-c0db-49cf-9f52-59a6459635b9\",\r\n        \"type\": \"message\",\r\n        \"timestamp\": \"2022-07-27T15:30:39.5787234+00:00\",\r\n        \"entry\": [\r\n            { ...\r\n            }\r\n        ]\r\n    }"
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            pattern: ^(VRDR|BFDR-BIRTH|BFDR-FETALDEATH)$
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema: { }
          application/json:
            schema: { }
          text/json:
            schema: { }
          application/*+json:
            schema: { }
      responses:
        '204':
          description: Content created
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
  '/STEVE/{jurisdictionId}/Bundles':
    get:
      tags:
        - Steve
      summary: "Retrieves outgoing messages for the jurisdiction\r\nIf the optional Certificate Number and Death year parameters are provided, retrieves all messages in history that match those given business ids."
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
        - name: _count
          in: query
          schema:
            type: integer
            format: int32
        - name: certificateNumber
          in: query
          schema:
            type: string
        - name: eventYear
          in: query
          schema:
            type: string
        - name: deathYear
          in: query
          schema:
            type: string
        - name: _since
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 1
      responses:
        '200':
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                additionalProperties: { }
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
    post:
      tags:
        - Steve
      summary: Submits a FHIR message to the API for processing
      description: "Sample request:\r\n            \r\n    POST\r\n            \r\n    {\r\n        \"resourceType\": \"Bundle\",\r\n        \"id\": \"bffdbf2e-c0db-49cf-9f52-59a6459635b9\",\r\n        \"type\": \"message\",\r\n        \"timestamp\": \"2022-07-27T15:30:39.5787234+00:00\",\r\n        \"entry\": [\r\n            { ...\r\n            }\r\n        ]\r\n    }"
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
        - name: vitalType
          in: path
          required: true
          schema:
            type: string
        - name: igVersion
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema: { }
          application/json:
            schema: { }
          text/json:
            schema: { }
          application/*+json:
            schema: { }
      responses:
        '204':
          description: Content created
        '400':
          description: Bad Request
        '500':
          description: 'Internal Error, token may have expired'
  '/STEVE/{jurisdictionId}/metadata':
    get:
      tags:
        - SteveCapabilityStatement
      parameters:
        - name: jurisdictionId
          in: path
          required: true
          schema:
            maxLength: 2
            minLength: 2
            type: string
      responses:
        '200':
          description: Success
components: { }