name: Update swagger

on:
  push:
    branches: [ swagger-page ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: |
        dotnet tool restore
        dotnet new tool-manifest --force
        dotnet tool install --version 6.4.0 Swashbuckle.AspNetCore.Cli 
    - name: Run Swagger Generation Scripts
      run: dotnet swagger "tofile" --output "${GITHUB_WORKSPACE}/swagger/v1/swagger.json" "${GITHUB_WORKSPACE}/messaging/bin/Debug/net6.0/messaging.dll" v1
    - name: Set up git config
      run: |
        git config user.name "GitHub Actions Swagger Docs Bot"
        git config user.email "<>"
    - name: commit changes
      run: |
        git checkout "${GITHUB_REF:11}"
        git add ./swagger/v1/swagger.yaml
        git add ./swagger/v1/swagger.json
        git commit -m "Swagger Bot - Update Swagger Documentation."
        git push
        
